eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
spring:
  zipkin:
    base-url: http://10.1.192.36:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1
logging:
  config: logback-spring.xml